name: Arch (ImageMagick7)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install base dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm base-devel git sudo

    - name: Install yay
      run: |
        useradd builduser -m
        passwd -d builduser
        printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
        sudo -u builduser bash -c 'cd ~ && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm'

    - name: Install ImageMagick
      run: |
        pacman -S --noconfirm imagemagick
        yay -S --noconfirm xtermcontrol

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: make
